version: "3.7"
services:
    todoapp:
        container_name: todo_server
        #pull: true
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        #volumes:
            #- ./usr/app/src